### ISSUE TITLE
Insert without image

### ISSUE THREAD

**Issue by Merce5** [AlexisEvol/PracticaFinalOpusListAlexis#1]
When I want to insert without an image or I open the FileChooser and I dont select an image throws this exception
[![Image from Gyazo](https://i.gyazo.com/78fd12b325cc9c4fa812a9ba2ef15e87.gif)](https://gyazo.com/78fd12b325cc9c4fa812a9ba2ef15e87)

**Comment by AlexisEvol** [comment]
He solucionado el problema añadiendo un if y un else que controlan que el txtImages tenga algo y sino ponga la imagen por defecto.

**Este trozo del código debe ser insertado justo debajo de la declaración del objeto Obra "obraNueva".**

            if(imagenesDeMas.contains(obraNueva.getImagen())){//Si la imagen seleccionada ya está en la carpeta images
                lblAviso.setText("Error! La imagen ya existe, cambia el nombre.");
            }
            else{//Si no lo está
                if (obraNueva.getRegistre() != null) {//Si el valor no es nulo
                        mainF.addToLista(obraNueva);//Añadimos el nuevo objeto Obra al ArrayList "lista"
                        this.setVisible(false);
                        if (obraNueva.getImagen().equals("")){
                            BufferedImage imagenDefecto = ImageIO.read(new File(System.getProperty("user.home") + "\\Documents\\NetBeansProjects\\PracticaFinalOpusListAlexis-main\\Gestor de Obras\\src\\spdvi\\ImagenesDefecto\\Defecto.jpg"));//BufferedImage de la imagen seleccionada
                            ImageIO.write(imagenDefecto, "jpg", new File(System.getProperty("user.home") + "\\AppData\\Local\\OpusList\\images\\Defecto.jpg"));//Guardamos la imagen en la carpeta images
                            obraNueva.setImagen("Defecto.jpg");
                        }
                        else{
                            String path = fchImagenChooser.getSelectedFile().getAbsolutePath();//El path de la imagen seleccionada
                            BufferedImage imagen = ImageIO.read(new File(path));//BufferedImage de la imagen seleccionada
                            ImageIO.write(imagen, "jpg", new File(System.getProperty("user.home") + "\\AppData\\Local\\OpusList\\images\\" + obraNueva.getImagen()));//Guardamos la imagen en la carpeta images
                        }
                        mainF.actualizador();
                }                
            }

**Comment by Merce5** [comment]
Please upload the changes :)

**Comment by AlexisEvol** [comment]
Everything is uploaded except the inserting the same register.

**Comment by Merce5** [comment]
Hello! When I try to insert the Opus it throws an exception.

https://user-images.githubusercontent.com/77398452/142193187-704238bd-1efe-4b23-9825-b086f839fb25.mp4

The problem is in the InsertDialog line 206, you have a path of your directory and I don't have that image. You should write only the relative path "src/spdvi/images/image.jpg"

![image](https://user-images.githubusercontent.com/77398452/142192990-07c07715-d38a-4b85-8be6-5f604028f233.png)

**Comment by Merce5** [comment]
Hello! When I try to insert the Opus it throws an exception.

https://user-images.githubusercontent.com/77398452/142193187-704238bd-1efe-4b23-9825-b086f839fb25.mp4

The problem is in the InsertDialog line 206, you have a path of your directory and I don't have that image. You should write only the relative path "src/spdvi/images/image.jpg"

![image](https://user-images.githubusercontent.com/77398452/142192990-07c07715-d38a-4b85-8be6-5f604028f233.png)

**Comment by AlexisEvol** [comment]
Commited, thank you for the heads up!
