### ISSUE TITLE
Update an Image

### ISSUE THREAD

**Issue by Merce5** [AlexisEvol/PracticaFinalOpusListAlexis#2]
When the Update window is open and I want to update the image it throws an error but it only happens with some images:
Error:
[![Image from Gyazo](https://i.gyazo.com/43072c4372148d254ef9f0f1d8e932cc.gif)](https://gyazo.com/43072c4372148d254ef9f0f1d8e932cc)
Without error:
[![Image from Gyazo](https://i.gyazo.com/216c01e22c27a0062051bedd32483387.gif)](https://gyazo.com/216c01e22c27a0062051bedd32483387)

**Comment by AlexisEvol** [comment]
El error estaba en que busca una imagen que aún no se había guardado. He cambiado el path que busca el ImageIO.read del btnUpdateAction de ChangeDialog

        String path = fchImagenChooser.getSelectedFile().getAbsolutePath();//El path de la imagen seleccionada
        
        for (Obra o: mainF.getLista()) {//recorremos la lista
            if (o.getRegistre().equals(txtRegistro.getText())) {//si el registro de la posición de la lista es igual al que está en el txt
                try {
                                       
                    //Añadiremos los nuevos valores al objeto que corresponda con el seleccionado previamente
                    o.setTitol(txtTitulo.getText());
                    o.setAny(txtYear.getText());
                    o.setFormat(txtFormato.getText());
                    o.setAutor(txtAutor.getText());
                    o.setImagen(txtImagen.getText());
                    BufferedImage imagen = ImageIO.read(new File(path));
                    ImageIO.write(imagen, "jpg", new File(System.getProperty("user.home") + "\\AppData\\Local\\OpusList\\images\\" + o.getImagen()));//Guardaremos la imagen del BufferedImage dentro de la carpeta images con el nombre que le corresponde
                } catch (IOException ex) {
                    Logger.getLogger(ChangeDialog.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

**Comment by Merce5** [comment]
Hello, please push the commit!!

**Comment by AlexisEvol** [comment]
Uploaded uwu

**Comment by Merce5** [comment]
All ok!
