### ISSUE TITLE
I can search a non-existing item and update it

### ISSUE THREAD

**Issue by Merce5** [AlexisEvol/PracticaFinalOpusListAlexis#3]
When I introduce a non-existing item in the item search the update dialog appears with no info:
[![Image from Gyazo](https://i.gyazo.com/b26243cac9fe5655555afb8fa84fcfc4.gif)](https://gyazo.com/b26243cac9fe5655555afb8fa84fcfc4)
And does not update nothing:
[![Image from Gyazo](https://i.gyazo.com/c3dd951208439638a7e0e4678b2a3c33.gif)](https://gyazo.com/c3dd951208439638a7e0e4678b2a3c33)

**Comment by AlexisEvol** [comment]
Hola Mercè, he encontrado una solución que parece funcionar para mi código por lo menos.

**En el main-form he cambiado el método ChangeDialog() por esto:**

        public void changeDialog(){//Lo usamos para abrir ChangeDialogUpdate
            if(bd.getEstadoRegistro() == true){
                cdu = new ChangeDialogUpdate(this, true);
                cdu.setVisible(true);
            }
        }

**En el SearchDialog he añadido esto al btnBuscarAction**

        for (Obra o: mainF.getLista()) {//Hacemos un for para recorrer todos los valores del ArrayList "lista"
            if (o.getRegistre().equals(txtRegistro.getText())) {//Si el registro de la posición de lista coincide con el que se ha escrito
                mainF.setRegistroNombre(txtRegistro.getText());//Le damos ese valor a la variable registroNombre con lo que hemos escrito
                existeRegistro = true;
                this.setVisible(false);
            }
            else{
                existeRegistro = false;
                System.out.println("Error, obra no encontrada");
                //Aquí pondré un lbl que tendrá el texto anterior
            }
        }

Pruébalo y dime si también te va.

**Comment by Merce5** [comment]
Hello, could you make a commit updating that changes instead of paste the code here?
Thank you!

**Comment by AlexisEvol** [comment]
It's uploaded

**Comment by Merce5** [comment]
The message is repeated too many times and you should change the System.out for a label in the GUI
![image](https://user-images.githubusercontent.com/77398452/142199902-e0e32ac9-edb6-45f9-9001-525a5e8e3d60.png)

**Comment by AlexisEvol** [comment]
Commited! thank you for the help! now it shows a text that will tell you "No existe"
