### ISSUE TITLE
Update without image

### ISSUE THREAD

**Issue by Merce5** [AlexisEvol/PracticaFinalOpusListAlexis#7]
Hello! When I try to update without image now it throws an error. The problem is that you take the image path from the file chooser directly, but if I dont choose any image the file chooser don't have any string and is null. You should make an string variable instead of the filechooser directly.

Something like this in the filechooser button :

<pre><code>int returnOption = fileChooser.showOpenDialog(this);
        if (returnOption == JFileChooser.APPROVE_OPTION) {
            mainForm.imagePath = fileChooser.getSelectedFile().getAbsolutePath();
        } else {
            mainForm.imagePath = "src/spdvi/icons/no_image.jpg";
        }
        try {
            BufferedImage image = ImageIO.read(new File(mainForm.imagePath));
            lblImage.setIcon(resizImageIcon(image));
        } catch (IOException ioe) {
            System.err.println("Error in btnSelectImage");
            System.err.println(ioe);
        }
</code></pre>

And then in the ChangeDialog line 206 you should change the String path = ... for String path = mainForm.imagePath;****

**Comment by AlexisEvol** [comment]
Hello! thank you for the advice, try it and tell me if it works properly now.

**Comment by Merce5** [comment]
Hello, it still doesn't work. You should initialize the String nombre in the changeDialog constructor like 

<pre><code>nombre = "src\\spdvi\\ImagenesDefecto\\Defecto.jpg";</code></pre>

Because if I don't click the changeImage button the String is never initialized

**Comment by AlexisEvol** [comment]
I made a little change that makes it more visual and also better in terms of logic. Thank you very much for the help!

![image](https://user-images.githubusercontent.com/77688934/142779125-4e6be336-fcf0-4d89-bc24-011930d18b77.png)

**Comment by Merce5** [comment]
Hello! You didn't do what I told you and that's why still doesn't working, you must initialize the variable name in the ChangeDialog constructor like this 
<pre><code>nombre = "src\\spdvi\\ImagenesDefecto\\Defecto.jpg";</code></pre>

**Comment by AlexisEvol** [comment]
Fixed, thank you! I added that if u update without changing anything; it's stays the same without poping an error.
